<a href="https://colab.research.google.com/github/subbu27iitb/AutoML/blob/main/Borouge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Apply TPOT AutoML**

In [2]:
!pip install tpot

     |████████████████████████████████| 87 kB 2.7 MB/s 
     |████████████████████████████████| 173.5 MB 11 kB/s 
     |████████████████████████████████| 160 kB 47.4 MB/s 
  Created wheel for stopit: filename=stopit-1.1.2-py3-none-any.whl size=11952 sha256=17a680a6fb5dc15bed01bf22c263bbdb29a262dd7fcd8510b2b669205727442b
  Stored in directory: /root/.cache/pip/wheels/e2/d2/79/eaf81edb391e27c87f51b8ef901ecc85a5363dc96b8b8d71e3
Successfully built stopit
  Attempting uninstall: xgboost
    Found existing installation: xgboost 0.90
    Uninstalling xgboost-0.90:
      Successfully uninstalled xgboost-0.90


In [3]:
from tpot import  TPOTClassifier
from sklearn.model_selection import train_test_split
from __future__ import print_function
import sys,tempfile, urllib, os
import pandas as pd
import numpy as np

In [81]:
from google.colab import files
uploaded = files.upload()

Saving Corrected1 Case-11 Data for Test.csv to Corrected1 Case-11 Data for Test.csv


In [83]:
comp_df=pd.read_csv('Corrected1 Case-11 Data for Test.csv')
print(comp_df.shape)
comp_df.head()

(163345, 9)


SNO  44LI5326  44PI5314  44PI5715  ...   44TI5305    44TI5366  44VI5329  target
0    0  0.015261  1.504713  0.293857  ...  34.244909  107.920075  0.227726     YES
1    1  0.015261  1.504241  0.295901  ...  34.257150  107.863101  0.229953     YES
2    2  0.015261  1.504437  0.295002  ...  34.242242  107.856428  0.226608     YES
3    3  0.015261  1.503716  0.294798  ...  34.257346  107.828389  0.226608     YES
4    4  0.015261  1.505843  0.296664  ...  34.241349  107.815481  0.225940     YES

[5 rows x 9 columns]

In [84]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(comp_df['target'])
type(y)
comp1 = pd.DataFrame(y, columns=['target'])
comp1.head(4)
comp_df.update(comp1)
comp_df.head()

SNO  44LI5326  44PI5314  44PI5715  ...   44TI5305    44TI5366  44VI5329  target
0    0  0.015261  1.504713  0.293857  ...  34.244909  107.920075  0.227726       1
1    1  0.015261  1.504241  0.295901  ...  34.257150  107.863101  0.229953       1
2    2  0.015261  1.504437  0.295002  ...  34.242242  107.856428  0.226608       1
3    3  0.015261  1.503716  0.294798  ...  34.257346  107.828389  0.226608       1
4    4  0.015261  1.505843  0.296664  ...  34.241349  107.815481  0.225940       1

[5 rows x 9 columns]

In [85]:
comp_df.head()

SNO  44LI5326  44PI5314  44PI5715  ...   44TI5305    44TI5366  44VI5329  target
0    0  0.015261  1.504713  0.293857  ...  34.244909  107.920075  0.227726       1
1    1  0.015261  1.504241  0.295901  ...  34.257150  107.863101  0.229953       1
2    2  0.015261  1.504437  0.295002  ...  34.242242  107.856428  0.226608       1
3    3  0.015261  1.503716  0.294798  ...  34.257346  107.828389  0.226608       1
4    4  0.015261  1.505843  0.296664  ...  34.241349  107.815481  0.225940       1

[5 rows x 9 columns]

In [86]:
comp_df.isna().sum()

SNO          0
44LI5326     0
44PI5314     0
44PI5715     0
44PIC5323    0
44TI5305     0
44TI5366     0
44VI5329     0
target       0
dtype: int64

In [87]:
print(comp_df.dtypes)

SNO            int64
44LI5326     float64
44PI5314     float64
44PI5715     float64
44PIC5323    float64
44TI5305     float64
44TI5366     float64
44VI5329     float64
target        object
dtype: object


In [88]:
col=list(comp_df.columns)
#type(col)
comp_df.loc[:,col] = pd.to_numeric(comp_df[col].values.ravel(),'coerce').reshape(-1,len(col)) #why errors = 'coerce' required ?

print(type(col))
print(comp_df.shape)
comp_df.dtypes

<class 'list'>
(163345, 9)


SNO          float64
44LI5326     float64
44PI5314     float64
44PI5715     float64
44PIC5323    float64
44TI5305     float64
44TI5366     float64
44VI5329     float64
target       float64
dtype: object

In [90]:
comp_df_X = comp_df.drop(["SNO", "target"], axis =1)
print(comp_df_X.head())
comp_df_y = comp_df["target"]
print(comp_df_y.head())

X_train, X_test, y_train, y_test = train_test_split(comp_df_X, comp_df_y, train_size=0.75, test_size=0.25)
print(y_test.head())

   44LI5326  44PI5314  44PI5715  44PIC5323   44TI5305    44TI5366  44VI5329
0  0.015261  1.504713  0.293857   2.716754  34.244909  107.920075  0.227726
1  0.015261  1.504241  0.295901   2.719369  34.257150  107.863101  0.229953
2  0.015261  1.504437  0.295002   2.721518  34.242242  107.856428  0.226608
3  0.015261  1.503716  0.294798   2.725866  34.257346  107.828389  0.226608
4  0.015261  1.505843  0.296664   2.722145  34.241349  107.815481  0.225940
0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
Name: target, dtype: float64
15876     1.0
110843    1.0
133134    1.0
147299    1.0
71927     1.0
Name: target, dtype: float64


**TPOT**

In [ ]:
tpot = TPOTClassifier(verbosity=2, max_time_mins=1)
tpot.fit(X_train, y_train)
print(tpot.score(X_test, y_test))

Imputing missing values in feature set


Optimization Progress:   0%|          | 0/100 [00:00<?, ?pipeline/s]



TPOT closed during evaluation in one generation.


TPOT closed prematurely. Will use the current best pipeline.


RuntimeError: ignored

In [ ]:
from tpot import TPOTClassifier
import multiprocessing

if __name__ == '__main__':
    multiprocessing.set_start_method('forkserver', force=True)
    tpot =  TPOTClassifier(generations=4, population_size=4, verbosity=3)
    tpot.fit(X_train, y_train)

32 operators have been imported by TPOT.
Imputing missing values in feature set


Optimization Progress:   0%|          | 0/20 [00:00<?, ?pipeline/s]


Generation 1 - Current Pareto front scores:

-1	0.9975756687933235	ExtraTreesClassifier(input_matrix, ExtraTreesClassifier__bootstrap=False, ExtraTreesClassifier__criterion=gini, ExtraTreesClassifier__max_features=0.7500000000000001, ExtraTreesClassifier__min_samples_leaf=1, ExtraTreesClassifier__min_samples_split=20, ExtraTreesClassifier__n_estimators=100)
_pre_test decorator: _random_mutation_operator: num_test=0 X contains negative values..

Generation 2 - Current Pareto front scores:

-1	0.9975756687933235	ExtraTreesClassifier(input_matrix, ExtraTreesClassifier__bootstrap=False, ExtraTreesClassifier__criterion=gini, ExtraTreesClassifier__max_features=0.7500000000000001, ExtraTreesClassifier__min_samples_leaf=1, ExtraTreesClassifier__min_samples_split=20, ExtraTreesClassifier__n_estimators=100)
Skipped pipeline #16 due to time out. Continuing to the next pipeline.

Generation 3 - Current Pareto front scores:

-1	0.9976899471778469	ExtraTreesClassifier(input_matrix, ExtraTreesClassi

**SVM**

**SVM Kernel:"Sigmoid"**

In [92]:
from sklearn.svm import SVC
SVModel = SVC(kernel = 'sigmoid', C=1, gamma = 'auto', probability = True)
SVModel.fit(X_train, y_train)

SVC(C=1, gamma='auto', kernel='sigmoid', probability=True)

In [93]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

print(confusion_matrix(y_train, SVModel.predict(X_train)))
print(accuracy_score(y_train, SVModel.predict(X_train)))
print(classification_report(y_train, SVModel.predict(X_train)))

[[     0   6386]
 [     0 116122]]
0.9478727919809319
              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00      6386
         1.0       0.95      1.00      0.97    116122

    accuracy                           0.95    122508
   macro avg       0.47      0.50      0.49    122508
weighted avg       0.90      0.95      0.92    122508



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


**SVM Kernel:"RBF"**



In [94]:
from sklearn.svm import SVC
SVModel = SVC(kernel = 'rbf', C=1, gamma = 'auto', probability = True)
SVModel.fit(X_train, y_train)

SVC(C=1, gamma='auto', probability=True)

In [95]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

print(confusion_matrix(y_train, SVModel.predict(X_train)))
print(accuracy_score(y_train, SVModel.predict(X_train)))
print(classification_report(y_train, SVModel.predict(X_train)))

[[  5739    647]
 [    67 116055]]
0.9941718091879714
              precision    recall  f1-score   support

         0.0       0.99      0.90      0.94      6386
         1.0       0.99      1.00      1.00    116122

    accuracy                           0.99    122508
   macro avg       0.99      0.95      0.97    122508
weighted avg       0.99      0.99      0.99    122508



In [96]:

print(confusion_matrix(y_test, SVModel.predict(X_test)))
print(accuracy_score(y_test, SVModel.predict(X_test)))
print(classification_report(y_test, SVModel.predict(X_test)))

[[ 1918   192]
 [   25 38702]]
0.9946861914440336
              precision    recall  f1-score   support

         0.0       0.99      0.91      0.95      2110
         1.0       1.00      1.00      1.00     38727

    accuracy                           0.99     40837
   macro avg       0.99      0.95      0.97     40837
weighted avg       0.99      0.99      0.99     40837

